version: '3.8'

services:
  app:
    build:
      context: .
    command: mix phx.server
    ports:
      - 5000:4000
    depends_on:
      - db
    volumes:
      - .:/app
      - app_node_modules:/app/assets/node_modules

  db:
    image: mariadb:10.10.2-jammy
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: maria
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
    ports:
      - 23306:3306
    volumes:
      - db_data:/var/lib/mariadb/data

volumes:
  app_node_modules:
  db_data:
